/*
include "../includes/License.as.inc";
 */

package temple.core.debug.log 
{
	import flash.events.Event;
	import temple.core.debug.objectToString;
	import temple.core.templelibrary;

	/**
	 * Event dispatched by the <code>Log</code> class when someting is logged. You can listen for this Event if you want
	 * to create your own Logger.
	 * 
	 * @see temple.core.debug.log.Log
	 * 
	 * @author Thijs Broerse
	 */
	public class LogEvent extends Event 
	{
		include "../../includes/Version.as.inc";
		
		/**
		 * Event type
		 */
		public static const EVENT:String = "LogEvent.Event";
		
		private static const _TO_STRING_PROPS:Vector.<String> = Vector.<String>(['level', 'data', 'sender', 'objectId']);

		private var _level:String;
		private var _data:*;
		private var _sender:String;
		private var _senderId:uint;
		private var _stackTrace:String;

		/**
		 * Creates a new LogEvent.
		 * @param level the level of the LogEvent.
		 * @param data data send with the Log message
		 * @param sender the 'toString' of the object that send the log message
		 * @param senderId the object id of the sender. The id is generated by the Registry.
		 */
		public function LogEvent(level:String, data:*, sender:String, senderId:uint, stackTrace:String = null) 
		{
			super(LogEvent.EVENT);
			
			this._level = level;
			this._data = data;
			this._sender = sender;
			this._senderId = senderId;
			this._stackTrace = stackTrace;
		}

		/**
		 * Returns the level of the Event.
		 * @see temple.core.debug.log.LogLevel
		 */
		public function get level():String
		{
			return this._level;
		}
		
		/**
		 * The data send with the Log message
		 */
		public function get data():*
		{
			return this._data;
		}
		
		/**
		 * The 'toString' of the object that send the log message
		 */
		public function get sender():String
		{
			return this._sender;
		}
		
		/**
		 * The id of the object that send the log message. The id is generated by the Registry.
		 * With the id you can get the object at the Registry
		 * @see temple.core.debug.Registry#getObject()
		 */
		public function get objectId():uint
		{
			return this._senderId;
		}
		
		/**
		 * The stack trace of the Log. To find the place where the message was logged.
		 * Only available if in debug players and if the this option is enabled in the Log.
		 */
		public function get stackTrace():String
		{
			return this._stackTrace;
		}
		
		/**
		 * Creates a copy of an existing LogEvent.
		 */
		override public function clone():Event 
		{
			return new LogEvent(this._level, this._data, this._sender, this._senderId);
		}
		
		/**
		 * @inheritDoc
		 */
		override public function toString():String 
		{
			return objectToString(this, _TO_STRING_PROPS);
		}
	}
}